<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <IsTestProject>true</IsTestProject>
        <WarnOn>FS1182</WarnOn>
        <WarningLevel>5</WarningLevel>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="M1ExperimentTests.fs" />
        <ProjectReference Include="../Blobbo Playground.fsproj" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
        <PackageReference Include="NUnit" Version="3.14.0" />
        <PackageReference Include="NUnit3TestAdapter" Version="4.5.0" />
    </ItemGroup>

</Project>